import './globals.css'
import type { Metadata } from 'next'

import { Work_Sans } from 'next/font/google'

import { cn } from '@/lib/utils'

const workSans = Work_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es">
      <body className={cn(workSans.className, 'flex text-sm')}>{children}</body>
    </html>
  )
}
