import type { Metadata } from 'next'

import { Sidebar } from '@/components/sidebar/sidebar'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function DashboardLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <Sidebar />
      {children}
      <Toaster />
    </>
  )
}
